-- ============================== --
--    ACID [creature_ai_texts]    --
-- ============================== --


ALTER TABLE `creature_ai_texts` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;



UPDATE `creature_ai_texts` SET `content_loc6`='Parece que esos idiotas de la Abadía nos han enviado carne fresca.' WHERE `entry`='-1';
UPDATE `creature_ai_texts` SET `content_loc6`='La Hermandad no tolerará tus actos.' WHERE `entry`='-2';
UPDATE `creature_ai_texts` SET `content_loc6`='Ah, una oportunidad para usar esta hoja recién afilada.' WHERE `entry`='-3';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Siente el poder de la Hermandad!' WHERE `entry`='-4';
UPDATE `creature_ai_texts` SET `content_loc6`='Más huesos para roer...' WHERE `entry`='-5';
UPDATE `creature_ai_texts` SET `content_loc6`='Grrrr... ¡carne fresca!' WHERE `entry`='-6';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Tú no llevarte vela!' WHERE `entry`='-7';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Yujuuuuuu! ¡Yo correr!.' WHERE `entry`='-8';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Qué significa esta impertinencia? ¡Moriréis!' WHERE `entry`='-9';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Gritad mientras ardeis!' WHERE `entry`='-10';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Os incineraré!' WHERE `entry`='-11';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Me regocijo con tu dolor!' WHERE `entry`='-12';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Quieres un premio, eh? ¿Qué tal la muerte?' WHERE `entry`='-13';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Tu vida será mia!' WHERE `entry`='-14';
UPDATE `creature_ai_texts` SET `content_loc6`='Odio recordarte que te avisé...' WHERE `entry`='-15';
UPDATE `creature_ai_texts` SET `content_loc6`='No iréis... muy lejos.' WHERE `entry`='-16';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Qué haceis? ¡Estos especímenes son muy delicados!' WHERE `entry`='-17';
UPDATE `creature_ai_texts` SET `content_loc6`='¡La naturaleza se somete a mi voluntad!' WHERE `entry`='-18';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Endorel aluminor!' WHERE `entry`='-19';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Ha concluido tu ciclo vital!' WHERE `entry`='-20';
UPDATE `creature_ai_texts` SET `content_loc6`='Hay que conservar... los especímenes...' WHERE `entry`='-21';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Van Cleef paga mucho por vuestras cabezas!' WHERE `entry`='-22';
UPDATE `creature_ai_texts` SET `content_loc6`='¡En guardia!' WHERE `entry`='-23';
UPDATE `creature_ai_texts` SET `content_loc6`='Defendeos, aunque no os servirá de mucho...' WHERE `entry`='-24';
UPDATE `creature_ai_texts` SET `content_loc6`='Lo sabía, sabía que... era la unica salida.' WHERE `entry`='-25';
UPDATE `creature_ai_texts` SET `content_loc6`='Si, muy satisfactorio.' WHERE `entry`='-26';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Al fin, un objetivo para mis frustraciones!' WHERE `entry`='-27';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Habéis venido para matar a Dalliah? ¿Puedo mirar?' WHERE `entry`='-28';
UPDATE `creature_ai_texts` SET `content_loc6`='La oscuridad... lo consume todo.' WHERE `entry`='-29';
UPDATE `creature_ai_texts` SET `content_loc6`='Las sombras... os engullirán.' WHERE `entry`='-30';
UPDATE `creature_ai_texts` SET `content_loc6`='Este... ya está vacío.' WHERE `entry`='-31';
UPDATE `creature_ai_texts` SET `content_loc6`='No... más... vida.' WHERE `entry`='-32';
UPDATE `creature_ai_texts` SET `content_loc6`='El vacío... se avecina.' WHERE `entry`='-33';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Dar un paso adelante! Os daré la bienvenida que os merecéis.' WHERE `entry`='-34';
UPDATE `creature_ai_texts` SET `content_loc6`='Oh, deja de lloriquear.' WHERE `entry`='-35';
UPDATE `creature_ai_texts` SET `content_loc6`='Aún no... he empezado...' WHERE `entry`='-36';
UPDATE `creature_ai_texts` SET `content_loc6`='Ya no os enfrentáis a un subordinado.' WHERE `entry`='-37';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Band\'or shorel\'aran!' WHERE `entry`='-38';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Guardias! ¡Reducir a los invasores!' WHERE `entry`='-39';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Es éste el final?' WHERE `entry`='-40';
UPDATE `creature_ai_texts` SET `content_loc6`='Qué llegará a ser de...' WHERE `entry`='-41';
UPDATE `creature_ai_texts` SET `content_loc6`='Ha llegado la hora de que te unas a nosotros, $C.' WHERE `entry`='-42';
UPDATE `creature_ai_texts` SET `content_loc6`='¡No!' WHERE `entry`='-43';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Estoy acabado!' WHERE `entry`='-44';
UPDATE `creature_ai_texts` SET `content_loc6`='El maestro... se enfadará...' WHERE `entry`='-45';
UPDATE `creature_ai_texts` SET `content_loc6`='¡%s se enfureció!' WHERE `entry`='-46';
UPDATE `creature_ai_texts` SET `content_loc6`='¡%s intenta huir despavorido!' WHERE `entry`='-47';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Habéis sido descubierto por el ojo de Grillok!' WHERE `entry`='-48';
UPDATE `creature_ai_texts` SET `content_loc6`='Espera... ¡No! ¡No!' WHERE `entry`='-49';
UPDATE `creature_ai_texts` SET `content_loc6`='No es... justo...' WHERE `entry`='-50';
UPDATE `creature_ai_texts` SET `content_loc6`='¡El destino se ha vuelto en mi contra!' WHERE `entry`='-51';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Dónde estoy? ¿Qué...' WHERE `entry`='-52';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Qué está pasando?' WHERE `entry`='-53';
UPDATE `creature_ai_texts` SET `content_loc6`='Lo... pagarás...' WHERE `entry`='-54';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Serás castigado!' WHERE `entry`='-55';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Cinco segundos! ¡No estoy bromeando!' WHERE `entry`='-56';
UPDATE `creature_ai_texts` SET `content_loc6`='Así que le dije: \"Sí, pero eso cuesta más.\"' WHERE `entry`='-57';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Podríamos haber tenido tanta diversión!' WHERE `entry`='-59';
UPDATE `creature_ai_texts` SET `content_loc6`='Voy a echar de menos el espectáculo.' WHERE `entry`='-61';
UPDATE `creature_ai_texts` SET `content_loc6`='Sí... Creo que ahora lo recuerdo...' WHERE `entry`='-62';
UPDATE `creature_ai_texts` SET `content_loc6`='Eso es todo... vuelve conmigo.' WHERE `entry`='-63';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Realmente se ha acabado?' WHERE `entry`='-64';
UPDATE `creature_ai_texts` SET `content_loc6`='Libre... al fin.' WHERE `entry`='-65';
UPDATE `creature_ai_texts` SET `content_loc6`='Es hora de seguir adelante...' WHERE `entry`='-66';
UPDATE `creature_ai_texts` SET `content_loc6`='La muerte es demasiado misericordiosa con vuestra especie.' WHERE `entry`='-67';
UPDATE `creature_ai_texts` SET `content_loc6`='Os espera la misma suerte a todos aquellos que intenten robar al maestro.' WHERE `entry`='-68';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Otro tomará mi lugar!' WHERE `entry`='-69';
UPDATE `creature_ai_texts` SET `content_loc6`='Esto... no cambia nada. ¡La condenación eterna te espera!' WHERE `entry`='-70';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Da la espalda mientras puedas!' WHERE `entry`='-71';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Sólo tendrás éxito condenandote a ti mismo!' WHERE `entry`='-72';
UPDATE `creature_ai_texts` SET `content_loc6`='Es poco aconsejable irritarme.' WHERE `entry`='-73';
UPDATE `creature_ai_texts` SET `content_loc6`='Tu estrategia era defectuosa.' WHERE `entry`='-81';
UPDATE `creature_ai_texts` SET `content_loc6`='Sí, el único resultado lógico.' WHERE `entry`='-82';
UPDATE `creature_ai_texts` SET `content_loc6`='Una contingencia... imprevista...' WHERE `entry`='-83';
UPDATE `creature_ai_texts` SET `content_loc6`='Mide dos veces, corta una.' WHERE `entry`='-84';
UPDATE `creature_ai_texts` SET `content_loc6`='Si he calculado bien, ¡estaréis bien muertos!' WHERE `entry`='-85';
UPDATE `creature_ai_texts` SET `content_loc6`='Pronostico una muerte dolorosa' WHERE `entry`='-86';
UPDATE `creature_ai_texts` SET `content_loc6`='Dispersáos mientras podáis.' WHERE `entry`='-87';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Rayos, soy genial!' WHERE `entry`='-88';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Matones!' WHERE `entry`='-89';
UPDATE `creature_ai_texts` SET `content_loc6`='Adelante, regaladme vuestro mejor golpe. ¡Lo resistiré!' WHERE `entry`='-90';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Creéis que me podéis hacer daño? ¿¡Qué os tengo miedo!?' WHERE `entry`='-91';
UPDATE `creature_ai_texts` SET `content_loc6`='¡El que avisa no es traidor!' WHERE `entry`='-92';
UPDATE `creature_ai_texts` SET `content_loc6`='¡El trabajo debe continuar!' WHERE `entry`='-93';
UPDATE `creature_ai_texts` SET `content_loc6`='¡No me obliguéis a mataros!' WHERE `entry`='-94';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Lo habéis provocado vosotros!' WHERE `entry`='-95';
UPDATE `creature_ai_texts` SET `content_loc6`='Tenía que hacerse.' WHERE `entry`='-96';
UPDATE `creature_ai_texts` SET `content_loc6`='No deberías haber venido.' WHERE `entry`='-97';
UPDATE `creature_ai_texts` SET `content_loc6`='Me... lo merezco.' WHERE `entry`='-98';
UPDATE `creature_ai_texts` SET `content_loc6`='Nunca despertarás al soñador.' WHERE `entry`='-99';
UPDATE `creature_ai_texts` SET `content_loc6`='¡%s deja ir un grito agudo pidiendo ayuda!' WHERE `entry`='-100';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Por los Faucedraco!' WHERE `entry`='-101';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Larga vida a los Faucedraco! ¡Que mueran sin valor, $r!' WHERE `entry`='-102';
UPDATE `creature_ai_texts` SET `content_loc6`='Cerebros...' WHERE `entry`='-103';
UPDATE `creature_ai_texts` SET `content_loc6`='Esta tierra pertenece a los enanos Hierro Negro. ¡Prepárate para ver el más allá, $c!' WHERE `entry`='-104';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Tus huesos se romperán bajo mi bota, $r!' WHERE `entry`='-105';
UPDATE `creature_ai_texts` SET `content_loc6`='¡%s entra en frenesí!' WHERE `entry`='-106';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Proteged a los inocentes!' WHERE `entry`='-107';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Sirve a la confianza pública!' WHERE `entry`='-108';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Mantened la ley!' WHERE `entry`='-109';
UPDATE `creature_ai_texts` SET `content_loc6`='¡%s explota, inundando la zona con residuos arcanos!' WHERE `entry`='-111';
UPDATE `creature_ai_texts` SET `content_loc6`='Tu mundo es nuestro ahora.' WHERE `entry`='-112';
UPDATE `creature_ai_texts` SET `content_loc6`='No puedo soportar más dolor. Tengo que encontrar una nueva fuente.' WHERE `entry`='-114';
UPDATE `creature_ai_texts` SET `content_loc6`='¿No has hecho ya suficiente daño? ¿Tienes que perturbar también mi sueño?' WHERE `entry`='-115';
UPDATE `creature_ai_texts` SET `content_loc6`='¿De qué sirve toda esta violencia? Lo hecho, hecho está. He fallado a mi pueblo.' WHERE `entry`='-116';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Abandonad toda esperanza! La Legión ha vuelto para acabar lo que se empezó hace tantos años... ¡Esta vez no habrá escapatoria!' WHERE `entry`='-117';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Reesh, hokta!' WHERE `entry`='-118';
UPDATE `creature_ai_texts` SET `content_loc6`='Solo es el principio... de lo que os espera...' WHERE `entry`='-119';
UPDATE `creature_ai_texts` SET `content_loc6`='No te esfuerzes...' WHERE `entry`='-120';
UPDATE `creature_ai_texts` SET `content_loc6`='Vuestro tiempo... casi se ha... agotado.' WHERE `entry`='-121';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Nadie va a salvarte!' WHERE `entry`='-122';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Soy el rey serpiente! Puedo obrar a mi antojo.' WHERE `entry`='-123';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Insolente!' WHERE `entry`='-124';
UPDATE `creature_ai_texts` SET `content_loc6`='La conquista final de la Legión está en marcha. De nuevo la subyugación de este mundo está a nuestro alcance. ¡Qué mueran todos!' WHERE `entry`='-125';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Sucumbid al frío helado... de la muerte!' WHERE `entry`='-126';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Hará más frío en vuestra tumba!' WHERE `entry`='-127';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Derrumbáos y pudríos!' WHERE `entry`='-128';
UPDATE `creature_ai_texts` SET `content_loc6`='Polvo sois, y en polvo os convertiréis.' WHERE `entry`='-129';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Toda forma de vida ha de perecer!' WHERE `entry`='-130';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Victoria para la Legión!' WHERE `entry`='-131';
UPDATE `creature_ai_texts` SET `content_loc6`='Habéis ganado esta batalla, pero no... la guerra...' WHERE `entry`='-132';
UPDATE `creature_ai_texts` SET `content_loc6`='Las espirales de la muerte... os aplastarán.' WHERE `entry`='-140';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Intrusos! ¡Sonad la alarma!' WHERE `entry`='-141';
UPDATE `creature_ai_texts` SET `content_loc6`='Athrikus vino a nosotros. Nos dijo que podía salvarnos del peligro. Lanzó un hechizo sobre nosotros para que nos protegiera de cualquier daño.' WHERE `entry`='-143';
UPDATE `creature_ai_texts` SET `content_loc6`='Cuando el temblor se detuvo, sus verdaderos motivos fueron revelados. Estábamos atrapados, y poco a poco fue drenando nuestra energía.' WHERE `entry`='-144';
UPDATE `creature_ai_texts` SET `content_loc6`='Había cientos de encarcelados por su hechizo. Ahora sólo unos pocos permanecen en sus cárceles. Él nos habla a veces sobre ello.' WHERE `entry`='-145';
UPDATE `creature_ai_texts` SET `content_loc6`='Le preocupaba que su poder se debilitara, incluso que su última piedra de alma se desvaneciera y muriera.' WHERE `entry`='-146';
UPDATE `creature_ai_texts` SET `content_loc6`='Su lugarteniente, Ilkurd Magthrull, posee un tomo que podría indicarnos la ubicación de las gemas de alma restantes.' WHERE `entry`='-147';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Fantástico! ¡Gracias!' WHERE `entry`='-148';
UPDATE `creature_ai_texts` SET `content_loc6`='¡%s se vuelve inestable y comienza a desintegrarse!' WHERE `entry`='-149';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Me ayudarás a encontrar a mi perro...?' WHERE `entry`='-150';
UPDATE `creature_ai_texts` SET `content_loc6`='Echo tanto de menos a mi perro...' WHERE `entry`='-151';
UPDATE `creature_ai_texts` SET `content_loc6`='¡%s crece en tamaño al ver a $N!' WHERE `entry`='-152';
UPDATE `creature_ai_texts` SET `content_loc6`='¡La fuerza de %s se desvanece!' WHERE `entry`='-153';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Illidan prevalecerá!' WHERE `entry`='-154';
UPDATE `creature_ai_texts` SET `content_loc6`='¡%s comienza a armar la bomba de proximidad!' WHERE `entry`='-155';
UPDATE `creature_ai_texts` SET `content_loc6`='¡La sangre es nuestro poder!' WHERE `entry`='-156';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Lok Narash!' WHERE `entry`='-157';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Por Kargath! ¡Por la victoria!' WHERE `entry`='-158';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Lok\'tar Illidari!' WHERE `entry`='-159';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Este mundo es NUESTRO!' WHERE `entry`='-160';
UPDATE `creature_ai_texts` SET `content_loc6`='Mmm... me encanta la deliciosa cerveza de Costasur.' WHERE `entry`='-162';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Acabad con ellos, hermanos! ¡Por la Plaga!' WHERE `entry`='-163';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Esclavizaremos a los jabaespínes!' WHERE `entry`='-164';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Nos extenderemos por esta tierra yerma!' WHERE `entry`='-165';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Pronto, la Plaga dominará el mundo!' WHERE `entry`='-166';
UPDATE `creature_ai_texts` SET `content_loc6`='¡MUERE!' WHERE `entry`='-167';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Quién se atreve a molestarme? ¡Muere, $N!' WHERE `entry`='-168';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Nadie puede enfrentárse a la Hermandad!' WHERE `entry`='-169';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Y no te levantes!' WHERE `entry`='-170';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Perritos falderos, todos vosotros!' WHERE `entry`='-171';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Ignorantes! ¡Nuestra causa es justa!' WHERE `entry`='-172';
UPDATE `creature_ai_texts` SET `content_loc6`='¡La Hermandad prevalecerá!' WHERE `entry`='-173';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Nos atacan! ¡A vuestros puestos, escoria! ¡Hay que rechazar al invasor!' WHERE `entry`='-174';
UPDATE `creature_ai_texts` SET `content_loc6`='Vosotros, marineros de agua dulce, sois más fuertes de lo que yo creía. ¡Tendré que improvisar!' WHERE `entry`='-175';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Me llenáis de ira!' WHERE `entry`='-176';
UPDATE `creature_ai_texts` SET `content_loc6`='Entretenedlos mientras suelto a los canes de guerra.' WHERE `entry`='-179';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Mis mascotas tienen hambre y se van a dar un festín con vuestra carne!' WHERE `entry`='-180';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Nosotros somos la verdadera Horda!' WHERE `entry`='-181';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Qué? Oh, no. No me importa lo que tengas que decirme. Estoy disfrutando con tu dolor.' WHERE `entry`='-183';
UPDATE `creature_ai_texts` SET `content_loc6`='Confiesa y serás libre.' WHERE `entry`='-185';
UPDATE `creature_ai_texts` SET `content_loc6`='¡%s llama a sus huargos!' WHERE `entry`='-187';
UPDATE `creature_ai_texts` SET `content_loc6`='Puedes llegar a tener mucho calor aquí, en las Tierras Inhóspitas. Pero al menos es un calor seco.' WHERE `entry`='-192';
UPDATE `creature_ai_texts` SET `content_loc6`='Algún día seré un chico de verdad.' WHERE `entry`='-194';
UPDATE `creature_ai_texts` SET `content_loc6`='Es peligroso estar aquí, maestro. Pero te ayudaré a montar guardia.' WHERE `entry`='-196';
UPDATE `creature_ai_texts` SET `content_loc6`='Podemos hacerlo mejor, más fuerte, más rápido. Tenemos la tecnología. Tenemos la magia.' WHERE `entry`='-197';
UPDATE `creature_ai_texts` SET `content_loc6`='Serás presa fácil, $c.' WHERE `entry`='-200';
UPDATE `creature_ai_texts` SET `content_loc6`='Mis garras destrozarán tu enclenque cuerpo, $r.' WHERE `entry`='-201';
UPDATE `creature_ai_texts` SET `content_loc6`='Haré de tu cabeza un trofeo, $r.' WHERE `entry`='-202';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Pan fresco a la venta!' WHERE `entry`='-204';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Pan recién horneado a la venta!' WHERE `entry`='-205';
UPDATE `creature_ai_texts` SET `content_loc6`='Tengo un mensaje especial para tí, $N. ¡Dice que debes morir!' WHERE `entry`='-209';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Muere en el nombre de Edwin VanCleef!' WHERE `entry`='-211';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Aaaahhhhhh!' WHERE `entry`='-212';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Aplastar!' WHERE `entry`='-213';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Matar!' WHERE `entry`='-214';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Destruir!' WHERE `entry`='-215';
UPDATE `creature_ai_texts` SET `content_loc6`='Matarte será fácil.' WHERE `entry`='-229';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Te morirás pronto!' WHERE `entry`='-230';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Te cortaré!' WHERE `entry`='-231';
UPDATE `creature_ai_texts` SET `content_loc6`='%s se centra en $N.' WHERE `entry`='-237';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Idiota! ¡La esencia del halcón nunca será tuya!' WHERE `entry`='-238';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Te atreves a molestar a los fieles seguidores del Cuervo?' WHERE `entry`='-240';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Morirás por tu arrogancia, druida!' WHERE `entry`='-241';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Te atreves a molestar a los fieles seguidores del Cuervo?' WHERE `entry`='-242';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Morirás por tu arrogancia, druida!' WHERE `entry`='-243';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Alguien puede leer el cartel de Se busca?. Grek no sabe leer.' WHERE `entry`='-244';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Grek lo prueba!' WHERE `entry`='-245';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Este aceite no es bueno para Grek! ¿Quién crees que es Grek, un montón de trapos sucios?' WHERE `entry`='-246';
UPDATE `creature_ai_texts` SET `content_loc6`='Grek toma un trago.' WHERE `entry`='-247';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Nunca pensé que podría llegar a hacer aceite de maná! No creo que haya mucha demanda de ello, menos por parte de Grek, por supuesto.' WHERE `entry`='-248';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Llévaselo!' WHERE `entry`='-249';
UPDATE `creature_ai_texts` SET `content_loc6`='Aprender a leer es un trabajo sediento. Un brindis, ¿vale?' WHERE `entry`='-250';
UPDATE `creature_ai_texts` SET `content_loc6`='%s se desmaya.' WHERE `entry`='-251';
UPDATE `creature_ai_texts` SET `content_loc6`='Ven aquí, $r. ¿No quieres correr riesgos en una mazmorra, verdad? El trabajo sucio, ¿y para qué? ¿Para algunas baratijas sin valor? No, lo que necesitas es uno de mis amuletos. ¡Garantizamos que funcionan!' WHERE `entry`='-252';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Hay peligros fuera de aquí, no? ¿Sabes lo que necesitas? Protección. ¡Puedo ayudarte a desafiar a la muerte! Tan solo usa esta piedra-fetiche del cuello, mira, ¡y luego ya podrás regresar del mundo de los espiritus! Un rápido viaje hasta tu cadáver y ya estarás de vuelta.' WHERE `entry`='-253';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Amuletos maravillosos! ¡Curiosidades increíbles! ¡La innovación en el trabajo de la joyería no tiene ningún paralelismo con los métodos, ya existentes, de la mística del viejo Griftah! ¡Prueba tu mismo estos encantos mágicos a unos precios razonables!' WHERE `entry`='-254';
UPDATE `creature_ai_texts` SET `content_loc6`='Juraría que habían más manzanas. ¡Grok!' WHERE `entry`='-255';
UPDATE `creature_ai_texts` SET `content_loc6`='Si nadie ayuda. ¡Grok aplasta!' WHERE `entry`='-256';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Hey! ¡Hola, $r! Tengo algo para ti. ¿Has visto a algún tikbalang? Espantosas criaturas, propensas al robo a distancia. Lo que necesitas es mi protector contra tikbalangs. ¡Garantizado para mantener alejados a todos tikbalangs!' WHERE `entry`='-258';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Grok necesita ayuda! ¿Por qué nadie ayuda?' WHERE `entry`='-259';
UPDATE `creature_ai_texts` SET `content_loc6`='Mog\'dorg el Marchito decir a Grok de ir a ciudad para ayudar a los Machacasangre. Grok ir.' WHERE `entry`='-260';
UPDATE `creature_ai_texts` SET `content_loc6`='El clan Aguja del Filo no pelea de manera justa. Tienen a los gronn de su lado. Ve a las Montañas Filospada y habla con Mog\'dorg el Marchito. Mata a los gronn.' WHERE `entry`='-261';
UPDATE `creature_ai_texts` SET `content_loc6`='Te veo cansado, $c. Creo que tengo algo para ti. Estos amuletos pueden ayudarte a saltar obstáculos y nadar a través de los ríos como si hubieras nacido para ello. Te permiten extraer gran cantidad de energía de la comida, ¡haciendo que las heridas se sanen delante de tus propios ojos!' WHERE `entry`='-262';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Qué hace ese pobre orco gritando? Alguien debería ver lo que está pasando.' WHERE `entry`='-263';
UPDATE `creature_ai_texts` SET `content_loc6`='Presiento que la guerra cada vez está más cerca. El vendedor de frutas ha reclutado a un ogro para ayudarle. Tendré que pedir ayuda también.' WHERE `entry`='-264';
UPDATE `creature_ai_texts` SET `content_loc6`='Me dan hambre. Parecen sabrosas esas frutas.' WHERE `entry`='-266';
UPDATE `creature_ai_texts` SET `content_loc6`='¡VENDEDOR DE FRUTAS! ¡Tu carro sigue en nuestro camino! Te daremos una hora más para sacarlo de nuestra zona. ¡No juegues con nuestra paciencia!' WHERE `entry`='-267';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Grok se enfada si los mequetrefes no van a Filospada y hablan con Mog\'dorg!' WHERE `entry`='-268';
UPDATE `creature_ai_texts` SET `content_loc6`='No hay nada como un buen pichel para mojar una de mis magníficas magdalenas.' WHERE `entry`='-269';
UPDATE `creature_ai_texts` SET `content_loc6`='Sí, has dado en el clavo. ¡Magdalenas a la venta! ¡Consigue tus magdalenas recién hechas aquí!' WHERE `entry`='-270';
UPDATE `creature_ai_texts` SET `content_loc6`='Sí, sí, soy el hombre de las magdalenas. ¿Sabes por qué? ¡Porqué vendo magdalenas!' WHERE `entry`='-271';
UPDATE `creature_ai_texts` SET `content_loc6`='Tengo magdalenas por aquí. ¡Ven!' WHERE `entry`='-272';
UPDATE `creature_ai_texts` SET `content_loc6`='Que así sea.' WHERE `entry`='-273';
UPDATE `creature_ai_texts` SET `content_loc6`='Anacoreta Nindumen, tengo una petición que hacerte.' WHERE `entry`='-274';
UPDATE `creature_ai_texts` SET `content_loc6`='Acabamos de enviar otro equipo sin experiencia a Nagrand. ¿Podrías orar por ellos?' WHERE `entry`='-275';
UPDATE `creature_ai_texts` SET `content_loc6`='Que así sea.' WHERE `entry`='-276';
UPDATE `creature_ai_texts` SET `content_loc6`='Por supuesto, amigo mío. ¿En que puedo ayudarte?' WHERE `entry`='-277';
UPDATE `creature_ai_texts` SET `content_loc6`='Una solicitud de nobles. Sería un honor, Erothem.' WHERE `entry`='-278';
UPDATE `creature_ai_texts` SET `content_loc6`='Amigos míos, por favor, uníos a mí en la humilde súplica a la Luz.' WHERE `entry`='-279';
UPDATE `creature_ai_texts` SET `content_loc6`='Luz que nos abrazas, te rogamos...' WHERE `entry`='-280';
UPDATE `creature_ai_texts` SET `content_loc6`='En nuestra lucha contra la oscuridad donde hemos enviado a nuestros hijos.' WHERE `entry`='-281';
UPDATE `creature_ai_texts` SET `content_loc6`='Por favor, bendícelos y protéjelos, y concédeles el éxito más que a los que buscan hacernos daño...' WHERE `entry`='-282';
UPDATE `creature_ai_texts` SET `content_loc6`='Continua la bendición para nuestra antigua casa, por favor.' WHERE `entry`='-283';
UPDATE `creature_ai_texts` SET `content_loc6`='Bendícenos con la tolerancia de nuestros visitantes elfos.' WHERE `entry`='-284';
UPDATE `creature_ai_texts` SET `content_loc6`='Por los Naaru, que así sea.' WHERE `entry`='-285';
UPDATE `creature_ai_texts` SET `content_loc6`='%s inclina la cabeza.' WHERE `entry`='-286';
UPDATE `creature_ai_texts` SET `content_loc6`='Hemos perdido parte de nuestros mejores soldados...' WHERE `entry`='-287';
UPDATE `creature_ai_texts` SET `content_loc6`='Pero eso no es lo peor de todo esto. Antes de que pudiéramos volver hacia atrás, uno de sus grupos nos vio y nos atacó.' WHERE `entry`='-288';
UPDATE `creature_ai_texts` SET `content_loc6`='No lo sé, ronco. No - lo - sé...' WHERE `entry`='-289';
UPDATE `creature_ai_texts` SET `content_loc6`='Orcos viles...' WHERE `entry`='-290';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Grandes bastardos rojos! ¡Más que cualquier otro orco que hayas visto antes! Los músculos por aquí, los colmillos por allá...' WHERE `entry`='-291';
UPDATE `creature_ai_texts` SET `content_loc6`='Y así fue, el explorador regresó inmediatamente advirtiéndonos de haber visto un par de orcos en el paso inferior. No nos habían visto todavía, así que imagino que no estarían informados.' WHERE `entry`='-292';
UPDATE `creature_ai_texts` SET `content_loc6`='Así que ahí estábamos - mi batallón y yo, haciendo un reconocimiento de rutina por el camino del hueso. Enviamos a un explorador más adelante para reconocer el terreno, en caso de que nos puediera sorprender algo.' WHERE `entry`='-293';
UPDATE `creature_ai_texts` SET `content_loc6`='Tómate esto, te ayudará.' WHERE `entry`='-344';
UPDATE `creature_ai_texts` SET `content_loc6`='Te pondrás bien.' WHERE `entry`='-345';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Yo machacar! ¡Tú morir!' WHERE `entry`='-360';
UPDATE `creature_ai_texts` SET `content_loc6`='¡¡Raaar!!! ¡Yo machacar $R!' WHERE `entry`='-361';
UPDATE `creature_ai_texts` SET `content_loc6`='Si el Capitán se entera, será mi fin.' WHERE `entry`='-414';
UPDATE `creature_ai_texts` SET `content_loc6`='Alguien tuvo que ayudarles.' WHERE `entry`='-415';
UPDATE `creature_ai_texts` SET `content_loc6`='De repente, estaban en todas partes.' WHERE `entry`='-416';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Kajanishu!' WHERE `entry`='-510';
UPDATE `creature_ai_texts` SET `content_loc6`='Arrrhhh... ¡Guardias!' WHERE `entry`='-548';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Guardias!' WHERE `entry`='-549';
UPDATE `creature_ai_texts` SET `content_loc6`='¡%s pide ayuda!' WHERE `entry`='-551';
UPDATE `creature_ai_texts` SET `content_loc6`='Saludos $Gciudadano:ciudadana;.' WHERE `entry`='-552';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Shaza-Kiel!' WHERE `entry`='-575';
UPDATE `creature_ai_texts` SET `content_loc6`='¡%s estará armado en 10 segundos!' WHERE `entry`='-579';
UPDATE `creature_ai_texts` SET `content_loc6`='¡%s estará armado en 5 segundos!' WHERE `entry`='-580';
UPDATE `creature_ai_texts` SET `content_loc6`='¡%s está armado!' WHERE `entry`='-581';
UPDATE `creature_ai_texts` SET `content_loc6`='¡¡SQUAWK!! *cough* *cough* ¡Tengo que dejar de fumar!' WHERE `entry`='-583';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Imposible!' WHERE `entry`='-597';
UPDATE `creature_ai_texts` SET `content_loc6`='¡De ningún modo!' WHERE `entry`='-617';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Dinos dónde se esconde tu líder!' WHERE `entry`='-655';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Por favor! Debo alimentarme de algo pronto... Un cristal de maná... un fragmento... ¡Cualquier cosa! ¡El dolor es insoportable!' WHERE `entry`='-656';
UPDATE `creature_ai_texts` SET `content_loc6`='¡No te daremos nada hasta que hables, escoria!' WHERE `entry`='-657';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Anaia?... ¿Me engañan mis ojos? ¿Eres tú de verdad?' WHERE `entry`='-661';
UPDATE `creature_ai_texts` SET `content_loc6`='El destino ha sido muy cruel al permitirnos volver a estar juntos solo tras miles de años de separación...' WHERE `entry`='-662';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Me odias, amor mío? Por haber tenido que destruir tu forma viviente y por liberar tu espíritu de tan triste cautiverio...' WHERE `entry`='-663';
UPDATE `creature_ai_texts` SET `content_loc6`='¡No! Anaia... ¡Anaia! ¡No me abandones! Por favor...' WHERE `entry`='-664';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Cómo, amor mío? ¿Cómo encontraré fuerzas para enfrentarme a las edades del mundo sin ti a mi lado...' WHERE `entry`='-665';
UPDATE `creature_ai_texts` SET `content_loc6`='El ha sido cruel con nosotros, amor mío, pero ten por seguro que ahora sí permaneceremos unidos.' WHERE `entry`='-666';
UPDATE `creature_ai_texts` SET `content_loc6`='No permitas que esto atormente tu corazón, amor mío. Me has liberado de la esclavitud y por ello te amo más aún.' WHERE `entry`='-667';
UPDATE `creature_ai_texts` SET `content_loc6`='Desafortunadamente, esto también debe interrumpirse... Los lazos que me atan a este mundo se debilitan y me arrastran...' WHERE `entry`='-668';
UPDATE `creature_ai_texts` SET `content_loc6`='Adiós, Cerellean, hasta que volvamos a reunirnos...' WHERE `entry`='-669';
UPDATE `creature_ai_texts` SET `content_loc6`='La suave voz de Anaia se desvanece entre la niebla, \"No olvides que siempre te amaré...\"' WHERE `entry`='-670';
UPDATE `creature_ai_texts` SET `content_loc6`='Se-Señora... ¿qui-quizás necesitó más po-polvo de cadáver...?' WHERE `entry`='-723';
UPDATE `creature_ai_texts` SET `content_loc6`='Se-Señora... ¿pu-puedo pu-pulir su... armadura?' WHERE `entry`='-724';
UPDATE `creature_ai_texts` SET `content_loc6`='Se-Señora... ¿Puedo ce-cepillar su po-poderoso corcel?' WHERE `entry`='-725';
UPDATE `creature_ai_texts` SET `content_loc6`='Sí, Se-Señora...' WHERE `entry`='-726';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Imposible!' WHERE `entry`='-742';
UPDATE `creature_ai_texts` SET `content_loc6`='¡JA!' WHERE `entry`='-753';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Abandonad este lugar!' WHERE `entry`='-764';
UPDATE `creature_ai_texts` SET `content_loc6`='Qué lástima que sobrevivieras al accidente para morir aquí.' WHERE `entry`='-902';
UPDATE `creature_ai_texts` SET `content_loc6`='¡No te permitiremos salir de este valle!' WHERE `entry`='-903';
UPDATE `creature_ai_texts` SET `content_loc6`='Espero que hayas hecho las paces.' WHERE `entry`='-904';
UPDATE `creature_ai_texts` SET `content_loc6`='¡No me cogerás viva, escoria!' WHERE `entry`='-905';
UPDATE `creature_ai_texts` SET `content_loc6`='Buhíco Cubrebosque inoculado no le gusta lo que ha sucedido.' WHERE `entry`='-906';
UPDATE `creature_ai_texts` SET `content_loc6`='El Buhíco Cubrebosque inoculado parece desorientado.' WHERE `entry`='-907';
UPDATE `creature_ai_texts` SET `content_loc6`='Buhíco Cubrebosque inoculado deambula sin rumbo fijo.' WHERE `entry`='-908';
UPDATE `creature_ai_texts` SET `content_loc6`='Buhíco Cubrebosque inoculado parece no importarle el efecto del cristal.' WHERE `entry`='-909';
UPDATE `creature_ai_texts` SET `content_loc6`='Buhíco Cubrebosque inoculado rebosa de alegría.' WHERE `entry`='-910';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Costasur pagará con sangre!' WHERE `entry`='-928';
UPDATE `creature_ai_texts` SET `content_loc6`='¡Me he alzado!' WHERE `entry`='-929';
UPDATE `creature_ai_texts` SET `content_loc6`='¡La venganza será mía al fin!' WHERE `entry`='-930';
UPDATE `creature_ai_texts` SET `content_loc6`='¿Fue... Fue todo un sueño? Isla Bruma Azur, Isla Bruma Sangre, Marisma de Zangar, Sombraluna... incluso Zul\'Aman... ¡Jane! ¡Jane dónde estás!' WHERE `entry`='-944';
UPDATE `creature_ai_texts` SET `content_loc6`='Estoy aquí, papi. Has estado dormido todo el día. ¡Debes estar bien cansado!' WHERE `entry`='-945';
UPDATE `creature_ai_texts` SET `content_loc6`='Ah, maravilloso. No fue mas que un sueño...' WHERE `entry`='-946';
