-- ========================= --
--      db_script_string     --
-- ========================= --



ALTER TABLE `db_script_string` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;

UPDATE `db_script_string` SET content_loc6='Desde siempre, los gavilanes han demostrado ser todo un éxito en la búsqueda de piedras del Cuervo. Vigía Elaira ha entrenado a otro para que oiga el silbato a una gran distancia. Él nos puede ayudar a comunicarnos a medida que vayas avanzando con tu búsqueda de las piedras.' WHERE entry=2000000000;
UPDATE `db_script_string` SET content_loc6='Como pensaba, la tabla tiene la confirmación que necesitamos. Ahora, tenemos que usar esta información para echar y derrotar a este Anzu antes de que pueda hacer más daño a Sueño Esmeralda!' WHERE entry=2000000001;
UPDATE `db_script_string` SET content_loc6='Hay algo más también. Después de una descripción de una sangrienta batalla y la caída del cuervo, hay una profecía. Anzu atormentará el sueño de sus enemigos, retorciéndolo para que afecte en su retorno a este mundo...' WHERE entry=2000000002;
UPDATE `db_script_string` SET content_loc6='Todo está aquí... como los seguidores del cuervo capturaron y sometieron la resistencia de sus enemigos, ¡Atrapándolos para siempre en estatuas de piedra! La tabla aún se lee el nombre del dios de cuervo -- Anzu. ¡Creía que la historia se había perdido!' WHERE entry=2000000003;
UPDATE `db_script_string` SET content_loc6='¡Así es! ¡Asi es en realidad el libro del Cuervo!' WHERE entry=2000000004;
UPDATE `db_script_string` SET content_loc6='Sin ti hubiésemos tardado años en encontrar el Libro del cuervo, joven gavilán. Vuelve con nuestra gratitud a tu hogar en Nagrand.' WHERE entry=2000000005;
UPDATE `db_script_string` SET content_loc6='¡Me siguen, $R! ¡Rápido, dime qué haces aquí antes de que nos descubran! ¡Si ellos me capturan, significará tu muerte y la mía!' WHERE entry=2000000006;
UPDATE `db_script_string` SET content_loc6='¡Tu no eres uno de ellos! ¡Salgamos de aquí antes de que nos descubran! ¡Aprisa!' WHERE entry=2000000007;
UPDATE `db_script_string` SET content_loc6='¿Qué haces en el reino de Ysera, intruso? ¡Déjanos, te digo! ¡Aquí no son  gratos los de tu clase!' WHERE entry=2000000008;
UPDATE `db_script_string` SET content_loc6='¡La amenaza ha acabado! ¡$N, todos nos salvamos!' WHERE entry=2000000009;
UPDATE `db_script_string` SET content_loc6='¿A cuántos más de vosotros he de gruñir y devolver a mami y papi en una mochila antes de que os crezca el cerebro y os deis cuenta de que correr frente a una escuadra de asesinos de la Legión es suicidarse? ¡Y no me encojáis los hombros que sabéis de lo que estoy hablando!' WHERE entry=2000000010;
UPDATE `db_script_string` SET content_loc6='Bien, así se hace. ¡A ver, volvamos a la tienda y acabemos nuestros negocios!' WHERE entry=2000000011;
UPDATE `db_script_string` SET content_loc6='Seguidme, buen $C. Voy a tener su barda más rápido de lo que se acaba una cerveza enana. Mmmm... negra.' WHERE entry=2000000012;
UPDATE `db_script_string` SET content_loc6='¡INCLINAOS ANTE EL TODO PODEROSO! ¡INCLINAOS ANTE MI INFERNAL DESTRUC...¿Gallina?' WHERE entry=2000000013;
UPDATE `db_script_string` SET content_loc6='¡Atrás! ¡Atrás! Tenemos que dejarle mucho espacio al infernal.' WHERE entry=2000000014;
UPDATE `db_script_string` SET content_loc6='¡Silencio, siervo! ¡La venganza será mía! ¡Muerte a Ventormenta! ¡Muerte por sobredosis de gallina!' WHERE entry=2000000015;
UPDATE `db_script_string` SET content_loc6='Gracias Gran espíritu. Gracias!' WHERE entry=2000000016;
UPDATE `db_script_string` SET content_loc6='Estas libre, $N.' WHERE entry=2000000017;
UPDATE `db_script_string` SET content_loc6='¡Gracias!' WHERE entry=2000000024;
UPDATE `db_script_string` SET content_loc6='¡Ok, vamos!' WHERE entry=2000000025;
UPDATE `db_script_string` SET content_loc6='Espíritus del agua, yo os bendigo, y pido vuestro amparo. Escuchad los ruegos de $N, y confiad en su noble intención. Por favor, ¿podéis ayudarnos?' WHERE entry=2000000026;
UPDATE `db_script_string` SET content_loc6='¡Vamos!.' WHERE entry=2000000027;
UPDATE `db_script_string` SET content_loc6='La gente de Páramos de poniente saludan a $N, un bravo y valiente defensor de la libertad.' WHERE entry=2000000028;
UPDATE `db_script_string` SET content_loc6='Esta es la tienda de Hollee, ¿pero donde está Hollee?' WHERE entry=2000000029;
UPDATE `db_script_string` SET content_loc6='Tampoco está aquí. que extraño... ¿Donde estará?' WHERE entry=2000000030;
UPDATE `db_script_string` SET content_loc6='Mmm. no está aquí. Tal vez Hollee esté...' WHERE entry=2000000031;
UPDATE `db_script_string` SET content_loc6='¡Oooooo calor calor calor! ¡Como no nos llegue la primavera, no se que voy a hacer!' WHERE entry=2000000033;
UPDATE `db_script_string` SET content_loc6='¡No hay nada como una infusión de albaza hirviendo en un día de Dun Morogh tan frio como el de hoy, para que empiecen bien las cosas!' WHERE entry=2000000035;
UPDATE `db_script_string` SET content_loc6='Toma una piedra de la tabla. La necesitarás para tu misión.' WHERE entry=2000000036;
UPDATE `db_script_string` SET content_loc6='¡Ayudamé, por favor!' WHERE entry=2000000037;
UPDATE `db_script_string` SET content_loc6='¡Eres mi héroe!' WHERE entry=2000000038;
UPDATE `db_script_string` SET content_loc6='Gracias por tu ayuda.' WHERE entry=2000000039;
UPDATE `db_script_string` SET content_loc6='OKay, Vamos!' WHERE entry=2000000040;
UPDATE `db_script_string` SET content_loc6='¡Escucháme, habitantes de Tanaris! Que se sepa que $n es un miembro exaltado de la orden de Mitril. Un herrero con honor, dedicación, y paciencia infinita. ¡Tres hurras por $n!' WHERE entry=2000000041;
UPDATE `db_script_string` SET content_loc6='Paciencia y paz estén contigo, $N. Permanece siempre fuerte.' WHERE entry=2000000042;
UPDATE `db_script_string` SET content_loc6='Hasta la próxima, valiente.' WHERE entry=2000000043;
UPDATE `db_script_string` SET content_loc6='Debes protegerme de los monstruos que viven en este bosque!' WHERE entry=2000000044;
UPDATE `db_script_string` SET content_loc6='Esta parte del bosque es muy peligrosa para nosotros. Debemos ser cautelosos!' WHERE entry=2000000045;
UPDATE `db_script_string` SET content_loc6='Mata a dos monstruos, que están cerca de la plantación de la ciénaga y entonces recolecto la ciénaga.' WHERE entry=2000000046;
UPDATE `db_script_string` SET content_loc6='Yo estoy recolectando la ciénaga. Me llevará algun tiempo.' WHERE entry=2000000047;
UPDATE `db_script_string` SET content_loc6='Pongamos esta extraña tierra en mi maceta...' WHERE entry=2000000048;
UPDATE `db_script_string` SET content_loc6='Gracias de nuevo, $N. Esta extraña tierra me resultará muy útil para mis experimentos.' WHERE entry=2000000049;
UPDATE `db_script_string` SET content_loc6='Bien, vale. Ahora te envio gente.¡Necesitamos encontrarle y ayudarle!.' WHERE entry=2000000050;
UPDATE `db_script_string` SET content_loc6='¿Tú sabes donde está? ' WHERE entry=2000000051;
UPDATE `db_script_string` SET content_loc6='¿Volcor se había ido? ' WHERE entry=2000000052;
UPDATE `db_script_string` SET content_loc6='¿Qué ocurre?' WHERE entry=2000000053;
UPDATE `db_script_string` SET content_loc6='¡Acercaté, novato!' WHERE entry=2000000054;
UPDATE `db_script_string` SET content_loc6='¡Mmm...No eres tan malo!' WHERE entry=2000000055;
UPDATE `db_script_string` SET content_loc6='La ciudad de Ventormenta se encuentra segura y protegida' WHERE entry=2000000133;
UPDATE `db_script_string` SET content_loc6='¡El enemigo no pasará!' WHERE entry=2000000134;
UPDATE `db_script_string` SET content_loc6='Orgrimmar se encuentra segura y protegida' WHERE entry=2000000137;
UPDATE `db_script_string` SET content_loc6='Darnassus se encuentra segura y protegida' WHERE entry=2000000140;
UPDATE `db_script_string` SET content_loc6='Forjaz se encuentra segura y protegida' WHERE entry=2000000142;
UPDATE `db_script_string` SET content_loc6='No creo que haya algún pez en estos canales' WHERE entry=2000000171;
UPDATE `db_script_string` SET content_loc6='¡Espero que sea un pez!' WHERE entry=2000000176;
UPDATE `db_script_string` SET content_loc6='Azul con rojo... Lo que me temía...' WHERE entry=2000001015;
UPDATE `db_script_string` SET content_loc6='¡Jamás se me hubiese ocurrido pensar que este aceite fuera maná! Oh, eso es todo lo que necesitas, a exepción de Grek, por supuesto.' WHERE entry=2000001020;
UPDATE `db_script_string` SET content_loc6='Escucha, caballero de la muerte... ¡Debes atender a la llamada de tu amo! ¡Él te está llamando!' WHERE entry=2000001058;
UPDATE `db_script_string` SET content_loc6='¡Llorica! ¡Llorica!' WHERE entry=2000005057;
UPDATE `db_script_string` SET content_loc6='¡La nena quiere su muñeca!' WHERE entry=2000005058;
UPDATE `db_script_string` SET content_loc6='¡Me pregunto si tu muñeca sabrá nadar!' WHERE entry=2000005059;
UPDATE `db_script_string` SET content_loc6='¡Ja, ja! ¡Tengo a Betsy!' WHERE entry=2000005060;
UPDATE `db_script_string` SET content_loc6='¡Tengo tu muñeca! ¡Chínchate!' WHERE entry=2000005062;
UPDATE `db_script_string` SET content_loc6='¡¡Dame mi muñeca!!' WHERE entry=2000005078;
UPDATE `db_script_string` SET content_loc6='¡Basta! ¡Le vas a arrancar la cabeza!' WHERE entry=2000005080;
UPDATE `db_script_string` SET content_loc6='¿Pero no fue eso lo que causó los problemas iniciales con la fórmula mágica de la Adepta Syleria?' WHERE entry=2000005155;
UPDATE `db_script_string` SET content_loc6='Sin embargo, esto generaría un desequilibrio en el centro mágico y causaría una vibración inversa en el éter.' WHERE entry=2000005159;
UPDATE `db_script_string` SET content_loc6='¿Pero no fue eso lo que causó los problemas iniciales con la fórmula mágica de la Adepta Syleria?' WHERE entry=2000005162;
UPDATE `db_script_string` SET content_loc6='¿Pero no fue eso lo que causó los problemas iniciales con la fórmula mágica de la Adepta Syleria?' WHERE entry=2000005166;
UPDATE `db_script_string` SET content_loc6='Si revertimos el flujo de la Esencia quizás podamos alterar la polaridad.' WHERE entry=2000005169;
UPDATE `db_script_string` SET content_loc6='¿Qué pasaría si utilizásemos tres focos de acuerdo con el patrón tireano? Eso lo resolvería.' WHERE entry=2000005170;
UPDATE `db_script_string` SET content_loc6='Vaya, todo esto para una poción de amor. Espero que él lo valga.' WHERE entry=2000005171;
UPDATE `db_script_string` SET content_loc6='Vaya, todo esto para una poción de amor. Espero que él lo valga.' WHERE entry=2000005174;
UPDATE `db_script_string` SET content_loc6='Pero si lo estabilizamos con un hilo de ancla en el nudo energético apropiado, tendría que funcionar.' WHERE entry=2000005175;
UPDATE `db_script_string` SET content_loc6='¿Qué pasaría si utilizásemos tres focos de acuerdo con el patrón tireano? Eso lo resolvería.' WHERE entry=2000005176;
UPDATE `db_script_string` SET content_loc6='Pero si lo estabilizamos con un hilo de ancla en el nudo energético apropiado, tendría que funcionar.' WHERE entry=2000005178;
UPDATE `db_script_string` SET content_loc6='Vaya, todo esto para una poción de amor. Espero que él lo valga.' WHERE entry=2000005179;
UPDATE `db_script_string` SET content_loc6='¿Tus estudios de magia te estresan? ¡Relájate en El Ermitaño Azul!' WHERE entry=2000005185;
UPDATE `db_script_string` SET content_loc6='¡Las mejores bebidas de Ventormenta!' WHERE entry=2000005186;
UPDATE `db_script_string` SET content_loc6='¡Las mejores bebidas de Ventormenta!' WHERE entry=2000005189;
UPDATE `db_script_string` SET content_loc6='¿Tus estudios de magia te estresan? ¡Relájate en El Ermitaño Azul!' WHERE entry=2000005190;
UPDATE `db_script_string` SET content_loc6='¡Pregúntame cómo conseguir una bebida gratis en El Ermitaño Azul!' WHERE entry=2000005191;
UPDATE `db_script_string` SET content_loc6='¡Bebidas gratis en El Ermitaño Azul!' WHERE entry=2000005193;
UPDATE `db_script_string` SET content_loc6='¿Tus estudios de magia te estresan? ¡Relájate en El Ermitaño Azul!' WHERE entry=2000005195;
UPDATE `db_script_string` SET content_loc6='¡Las mejores bebidas de Ventormenta!' WHERE entry=2000005196;
UPDATE `db_script_string` SET content_loc6='¡Pregúntame cómo conseguir una bebida gratis en El Ermitaño Azul!' WHERE entry=2000005197;
UPDATE `db_script_string` SET content_loc6='¡Las mejores bebidas de Ventormenta!' WHERE entry=2000005199;
UPDATE `db_script_string` SET content_loc6='Estos fuegos no han cesado durante años. Inusual esmero para los Trolls.' WHERE entry=2000005237;
